from pathlib import Path

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

REPORT_DIR = Path("reports")
REPORT_DIR.mkdir(exist_ok=True)


def generate_pdf(prediction, explanation):

    filename = REPORT_DIR / f"report_{prediction.id}.pdf"

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]

    body = styles["BodyText"]

    doc = SimpleDocTemplate(str(filename))

    story = []

    # ================= TITLE =================

    story.append(
        Paragraph(
            "SentinelMail AI Report",
            title_style
        )
    )

    story.append(Spacer(1, 20))

    # ================= DETAILS =================

    story.append(
        Paragraph(
            f"<b>Date :</b> {prediction.created_at.strftime('%d %b %Y %I:%M %p')}",
            body
        )
    )

    story.append(
        Paragraph(
            f"<b>Prediction :</b> {prediction.prediction}",
            body
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence :</b> {prediction.confidence:.2f}%",
            body
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk :</b> {prediction.risk}",
            body
        )
    )

    story.append(Spacer(1, 18))

    # ================= AI ANALYSIS =================

    story.append(
        Paragraph(
            "AI Security Analysis",
            heading
        )
    )

    story.append(
        Paragraph(
            explanation.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 18))

    # ================= ORIGINAL MESSAGE =================

    story.append(
        Paragraph(
            "Original Message",
            heading
        )
    )

    story.append(
        Paragraph(
            prediction.message.replace("\n", "<br/>"),
            body
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            "<b>Generated by SentinelMail AI</b>",
            body
        )
    )

    doc.build(story)

    return filename